FROM node:18.19.0-bullseye-slim

WORKDIR /home/learnbestia_frontend/src

COPY frontend/package.json frontend/package-lock.json ./
RUN npm install

COPY frontend .

EXPOSE 3000

CMD ["npm", "run", "dev"]